# Generated by Django 5.1.5 on 2025-02-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='posts',
            field=models.ManyToManyField(related_name='catalogs', to='posts.post'),
        ),
    ]
